### ISSUE TITLE
two line labels on y-axis

### ISSUE THREAD

**Issue by mkaulisch** [asjadnaqvi/stata-streamplot#13]
In my example using streamplot I have a difficulty with the textsize of the labels. I most likely need to revert to abbreviation of labels in order to keep graph size reasonable. Thus, I wonder if it would be possible to allow labels to span two or more lines.
At the moment a scatter-plot-marker-label solution is used but wouldn't it be possible to use a y-axis-label solution that allows for multiple lines?

**Comment by asjadnaqvi** [comment]
The two line solution can work in some circumstances, but without a generic label wrapping option (this is currently a work-in-progress), it becomes problematic, especially if there are a lot of very small groups.

One way is to extend the axis range using the offset option that allows for accomodating larger labels.

**Comment by mkaulisch** [comment]
Oh great, are you working on a label wrapping option? I am only able to do it with Graph Editor but not with -xlabel- option. I will post a question on Statalist about it.

**Comment by mkaulisch** [comment]
is this now fixed with the new version 1.82?

**Comment by asjadnaqvi** [comment]
Yes!

```
streamplot new_cases date if date > 22400, by(region) smooth(6) lc(white) palette(CET C6) ///
	labcond(20000) labsize(1.8) lw(0.04) wrap(20)
```


![test_wrap](https://github.com/asjadnaqvi/stata-streamplot/assets/38498046/6ef3fc97-42d4-4a50-9121-de3a951a87c2)

**Comment by mkaulisch** [comment]
Cool and thank you for bringing it also to the other graph ados.
