### ISSUE TITLE
Labels from by-variable not shown

### ISSUE THREAD

**Issue by mkaulisch** [asjadnaqvi/stata-streamplot#4]
In my example do-file the labels of the by-variable values are not shown as ylabels. Only the by-variables values (1,2,3,4,5) plus the values in brackets are displayed and not the respective labels. Asjad has reproduced the issue provided on Discord. The examples in the help file work just fine.

**Comment by asjadnaqvi** [comment]
This has been fixed in v1.2 update on 14th June 2022.
