### ISSUE TITLE
marker label displayed beyond graph region

### ISSUE THREAD

**Issue by mkaulisch** [asjadnaqvi/stata-streamplot#6]
In my example the marker label (pseudo ylabels) are cut at end of graph region. Thus not all information (values) are shown.
See 
![grafik](https://user-images.githubusercontent.com/73936880/173771724-b78250ac-5365-4b5a-8292-eae07f334386.png)

Not sure if that is fixable at program level.

**Comment by asjadnaqvi** [comment]
This is expected behavior especially if the labels are very long. There is a streamplot option **offset()** that extends the region to allow long labels. The default value is offset(0.12), which implies 12% of the width of the x-axis. You can increase this using offset(0.2) or higher values.

**Comment by mkaulisch** [comment]
ah, great. It works.
