### ISSUE TITLE
mlabcolor not the same as fcolor

### ISSUE THREAD

**Issue by mkaulisch** [asjadnaqvi/stata-streamplot#7]
In my example, picture given in #6 , the marker label color is different from area fill color.
My proposal is to use the colorpalette in marker label color if option -ylabcolor- is empty.

In my case the colors provided by the colorpalette specified are in a different sort order than those provided by the scheme. I am not sure if the two interfere with each other in this case.

**Comment by mkaulisch** [comment]
Code is integrated. So issue is closed.

**Comment by asjadnaqvi** [comment]
added.
